### PR TITLE
update the tag format for grahite client

### PR DESCRIPTION
**Pull request by liukun4515**
Signed-off-by: liukun4515 <liukun@apache.org>

Closes https://github.com/prometheus/client_java/issues/664

### CODE REVIEW

**Comment by liukun4515** [comment]
@fstab PTAL

**Review by fstab — APPROVED** [review]
Thanks a lot!

**Review by fstab — CHANGES_REQUESTED** [review]
Sorry, I approved too early. There's a `GraphiteTest` that's failing after your change. I assume the test is wrong, as it expects output `labels.l.fo_o` but after your change the output is `labels;l=fo_o`. Could you adapt the test, and signoff? Thanks

**Comment by liukun4515** [comment]
> Sorry, I approved too early. There's a `GraphiteTest` that's failing after your change. I assume the test is wrong, as it expects output `labels.l.fo_o` but after your change the output is `labels;l=fo_o`. Could you adapt the test, and signoff? Thanks

Thanks, the test has been resolved 
cc @fstab

**Comment by fstab** [comment]
Thanks a lot!

**Pull request merged**
