### PR TITLE
Use foreach loop where possible

### PR DESCRIPTION
**Pull request by Jubobs**
Addresses #228.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This code is copied from upstream, we don't change it.

**Comment by Jubobs** [comment]
@brian-brazil What do you mean by "upstream" in this context?

**Comment by brian-brazil** [comment]
Actually TimeWindowQuantiles is ours so we can change that, I was thinking of its dependency.

See the file themselves for where we got the other two.

**Comment by Jubobs** [comment]
Gotcha. I've amended my PR accordingly.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
