### PR TITLE
slightly decrease thread contention by synchronizing once rather than…

### PR DESCRIPTION
**Pull request by t3hnar**
Improve Summary: slightly decrease thread contention by synchronizing once rather than "number quantiles + 1" times

### CODE REVIEW

**Comment by rrakos-evo** [comment]
It looks like this doesn't make a significant difference. 🙁 

Benchmark:
```
# JMH version: 1.21
# VM version: JDK 11.0.2, OpenJDK 64-Bit Server VM, 11.0.2+9
# VM invoker: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java
# VM options: -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=49590:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8
# Warmup: 5 iterations, 10 s each
# Measurement: 4 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 24 threads, will synchronize iterations
```
Please take the results with a grain of salt.

Before - 4e0e7527:
```
Benchmark                                                           Mode  Cnt       Score        Error  Units
SummaryBenchmark.codahaleHistogramBenchmark                         avgt    4    5449.211 ±    157.085  ns/op
SummaryBenchmark.prometheusSimpleHistogramBenchmark                 avgt    4     219.256 ±     23.811  ns/op
SummaryBenchmark.prometheusSimpleHistogramChildBenchmark            avgt    4      88.585 ±      1.734  ns/op
SummaryBenchmark.prometheusSimpleHistogramNoLabelsBenchmark         avgt    4      83.989 ±      2.093  ns/op
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     186.796 ±     15.029  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      61.782 ±      5.032  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      59.388 ±     12.457  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  530692.958 ± 627614.926  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  563807.323 ± 389413.917  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  559719.005 ± 631676.260  ns/op
```

After - c726b1a7:
```
Benchmark                                                           Mode  Cnt       Score        Error  Units
SummaryBenchmark.codahaleHistogramBenchmark                         avgt    4    5651.711 ±    487.476  ns/op
SummaryBenchmark.prometheusSimpleHistogramBenchmark                 avgt    4     220.865 ±     11.554  ns/op
SummaryBenchmark.prometheusSimpleHistogramChildBenchmark            avgt    4      95.237 ±      6.059  ns/op
SummaryBenchmark.prometheusSimpleHistogramNoLabelsBenchmark         avgt    4      87.088 ±     15.551  ns/op
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     196.351 ±     33.766  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      60.853 ±      9.388  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      64.209 ±      2.437  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  525567.096 ± 599616.355  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  724240.526 ± 864857.588  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  703944.682 ± 906458.910  ns/op
```
I picked the result with the smallest error from multiple benchmark runs.

Quantiles:
```
  .quantile(0.5, 0.05).quantile(0.9, 0.05).quantile(0.95, 0.01).quantile(0.99, 0.005)
```

**Comment by brian-brazil** [comment]
It likely needs a different benchmark design for this to show up.

**Comment by t3hnar** [comment]
@brian-brazil is there something which stops you from accepting this PR ? how can I improve this?

**Comment by brian-brazil** [comment]
I still have to do a proper review, however the benchmarks are not
conclusive. Try a benchmark that rotates frequently.

**Comment by rrakos-evo** [comment]
It looks like this doesn't make a significant difference. 🙁

Before - 4e0e752 - `maxAgeSeconds=600, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score         Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     219.757 ±      61.084  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      81.192 ±      42.157  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      71.233 ±      10.217  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  544183.558 ±  673721.964  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  604961.225 ± 1102601.976  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  611718.456 ±  961269.567  ns/op
```

After - c726b1a - `maxAgeSeconds=600, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score         Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     252.022 ±     161.467  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      69.318 ±       9.407  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      70.984 ±       8.715  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  508342.249 ±  367462.250  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  661664.689 ±  739166.750  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  697726.672 ± 1409700.286  ns/op
```

Before - 4e0e752 - `maxAgeSeconds=60, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score        Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     213.747 ±      7.583  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      66.990 ±      6.503  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      77.389 ±      9.192  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  259765.997 ± 358709.484  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  317509.004 ± 596762.748  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  324706.634 ± 382327.655  ns/op
```

After - c726b1a - `maxAgeSeconds=60, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score        Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     231.908 ±     45.979  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      74.272 ±      8.909  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      72.157 ±      4.310  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  352584.198 ± 191647.019  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  411203.918 ± 596264.924  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  410841.897 ± 505489.988  ns/op
```

Before - 4e0e752 - `maxAgeSeconds=6, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score       Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     246.210 ±    17.015  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      67.433 ±    10.148  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      70.137 ±    10.208  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  106283.964 ± 59817.072  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  117276.079 ± 15151.896  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  112516.505 ± 48298.023  ns/op
```

After - c726b1a - `maxAgeSeconds=6, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt       Score       Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4     225.264 ±    57.002  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4      64.463 ±     2.153  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4      66.457 ±     1.970  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  114767.996 ± 40131.263  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  126502.374 ± 30720.763  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  131050.590 ± 65970.924  ns/op
```

Before - 4e0e752 - `maxAgeSeconds=1, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt      Score       Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    226.792 ±    51.313  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     67.871 ±    10.559  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     68.260 ±     6.567  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  45594.702 ± 12321.879  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  48994.075 ±  3317.460  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  47073.086 ±  5388.792  ns/op
```

After - c726b1a - `maxAgeSeconds=1, ageBuckets=5`:
```
Benchmark                                                           Mode  Cnt      Score       Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    213.242 ±    51.151  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     67.623 ±    20.423  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     69.312 ±     8.655  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  46977.894 ± 21980.921  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  44708.777 ± 11136.298  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  45772.478 ±  7892.974  ns/op
```

It makes sense to me that more frequent rotations (shorter time window) is faster, as there are less measurements and samples (for `CKMSQuantiles`).

**Comment by rrakos-evo** [comment]
Benchmarks with unrealistically frequent rotations by hardcoding `TimeWindowQuantiles. durationBetweenRotates`.

The results were consistent across many runs over the last 2 days.

Before - 4e0e7527 - `durationBetweenRotates=1ms`:
```
Benchmark                                                           Mode  Cnt      Score      Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    180.660 ±   31.025  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     59.794 ±    2.183  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     62.603 ±    2.560  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  16668.278 ±  899.351  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  16473.560 ± 1271.724  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  16279.621 ± 1513.338  ns/op
```

After - c726b1a7 - `durationBetweenRotates=1ms`:
```
Benchmark                                                           Mode  Cnt      Score      Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    188.946 ±   23.181  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     59.379 ±    2.877  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     59.461 ±    1.214  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  14943.023 ± 1479.789  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4   9085.545 ±  778.160  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4   9181.785 ±  976.102  ns/op
```

Before - 4e0e7527 - `durationBetweenRotates=100us`:
```
Benchmark                                                           Mode  Cnt      Score     Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    190.128 ±  37.522  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     59.393 ±   1.586  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     62.860 ±   7.727  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  12261.290 ± 206.572  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4  12279.661 ± 117.961  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4  12317.630 ± 270.580  ns/op
```

After - c726b1a7 - `durationBetweenRotates=100us`:
```
Benchmark                                                           Mode  Cnt      Score     Error  Units
SummaryBenchmark.prometheusSimpleSummaryBenchmark                   avgt    4    184.783 ±  29.702  ns/op
SummaryBenchmark.prometheusSimpleSummaryChildBenchmark              avgt    4     59.636 ±   1.406  ns/op
SummaryBenchmark.prometheusSimpleSummaryNoLabelsBenchmark           avgt    4     61.560 ±   2.485  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesBenchmark          avgt    4  12279.452 ±  29.655  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesChildBenchmark     avgt    4   7940.067 ± 590.255  ns/op
SummaryBenchmark.prometheusSimpleSummaryQuantilesNoLabelsBenchmark  avgt    4   7320.339 ± 260.343  ns/op
```

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
