### PR TITLE
Bump up caffeine dependencies

### PR DESCRIPTION
**Pull request by eschizoid**
The purpose of this PR is to add support for the `AsyncCache` and not only the`AsyncLoadingCache`

### CODE REVIEW

**Comment by eschizoid** [comment]
hey @checketts wondering if you can give it a quick look to this little guy, thanks!

**Comment by brian-brazil** [comment]
We purposefully list old versions so that we don't inadvertently break backwards compatibility.

**Comment by eschizoid** [comment]
>We purposefully list old versions so that we don't inadvertently break backwards compatibility.

hey @brian-brazil thanks for your quick reply. Is there any other we can add support for this new type of caching that caffeine supports?

This upgrade should be breaking previous implementations since now both classes shared a common interface, hope that helps :)

**Comment by brian-brazil** [comment]
So if someone was running 2.3.0, then this wouldn't break them?

**Comment by eschizoid** [comment]
hey @brian-brazil attached my answers.

>So if someone was running 2.3.0, then this wouldn't break them?
Thats is correct, given the following interface:

```
package com.github.benmanes.caffeine.cache;
..
public interface AsyncLoadingCache<K, V> extends AsyncCache<K, V> {
...
}
```

Caffeine now offers some other methods that allow you to have an instance `AsyncCache`

**Comment by brian-brazil** [comment]
I'm not convinced, there is no AsyncCache in 2.3.0.

**Comment by eschizoid** [comment]
> I'm not convinced, there is no AsyncCache in 2.3.0.
correct, so folks that remain on version 0.8.1 won't have problems


let's say we merge this PR and folks migrate to version 0.8.2, they won't have to change their working code since `AsyncCache` is the base class for `AsyncLoadingCache `, meaning they won't have to change their code at all other than bumping the dependency.

Would it be helpful if add some explanations on the REAMDE file explaining how inheritance works in java and add some examples of how to migrate to the new version?

If you feel more comfortable we can also do this :)


```
public void addCache(String cacheName, AsyncLoadincCache cache) {
    public void addCache(String cacheName, AsyncLoadincCache cache) {
        children.put(cacheName, cache.synchronous());
    }

public void addCache(String cacheName, AsyncCache cache) {
    public void addCache(String cacheName, AsyncCache cache) {
        children.put(cacheName, cache.synchronous());
    }
```

i feel is a little bit redundant given what i explain, please let me know what you think :)

**Comment by brian-brazil** [comment]
> correct, so folks that remain on version 0.8.1 won't have problems

But folks who upgrade to the next version of client_java would. I don't like forcing users to upgrade to new versions of dependencies unless there's a non-trivial gain in terms of the metrics available. Especially when the new version hasn't even been out two weeks yet.

**Comment by eschizoid** [comment]
> I don't like forcing users to upgrade to new versions of dependencies unless there's a non-trivial gain in terms of the metrics available.

I see. I think t the java client will get some benefits on the metric side since now it will support the two types of caches.

> Especially when the new version hasn't even been out two weeks yet.

What about if we bump up to the version where the interface `AsyncCache` was introduced?

**Comment by brian-brazil** [comment]
That sounds more reasonable.

**Comment by eschizoid** [comment]
>That sounds more reasonable.
Done :)

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
