### PR TITLE
Better metric name sanitizer in Dropwizard exporter

### PR DESCRIPTION
**Pull request by apesternikov**
Fix for (https://github.com/prometheus/client_java/issues/313)
@brian-brazil please review.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

**Comment by johnrengelman** [comment]
Is there a chance this could get release in a patch release (0.1.1?) Trying to integrate prometheus into github.com/ratpack/ratpack and we need to deal with metrics that start with a digit.

**Comment by brian-brazil** [comment]
I'll put a release on my todo list.

**Comment by johnrengelman** [comment]
^ any idea when this might happen? Would be really helpful.

**Pull request merged**
