### PR TITLE
Various cleanups in instrumentation-jvm

### PR DESCRIPTION
**Pull request by mimaison**
Same as #1012, let's see if the build runs here

### CODE REVIEW

**Comment by mimaison** [comment]
Here the build fails because of spotless issues in te prometheus-metrics-model module which this PR does not touch: https://github.com/mimaison/client_java/actions/runs/11127458358/job/30919802107

**Comment by zeitlinger** [comment]
> Here the build fails because of spotless issues in the prometheus-metrics-model module which this PR does not touch: https://github.com/mimaison/client_java/actions/runs/11127458358/job/30919802107

problem seems to be that the action runs in your repo - where `origin/main` is different - that's why the build check here is not working

**Comment by zeitlinger** [comment]
> > I wonder if we should apply spotless across the whole project at once, and then restart working on code changes.
> 
> wondering that too - makes it easier to review changes

done - https://github.com/prometheus/client_java/pull/1015

**Comment by mimaison** [comment]
Awesome, let me rebase!

**Pull request closed without merging**
