### PR TITLE
Add checks for invalid metric names and labels.

### LINKED ISSUE #28: Metric and label names should be checked for validity
Reporting this because users placed a dash into a metric name, which was then not queriable via Prometheus (the query language cannot tell a dash/minus apart).

The client library should check that metric and label names are valid ones that can be queried through the query language later (and we should add the same check upon ingestion in Prometheus):

Metric names have to adhere to this regex:

- `[a-zA-Z_:]([a-zA-Z0-9_:])*`

Similarly, label names need need to adhere to this one (basically, no colons allowed):

- `[a-zA-Z_]([a-zA-Z0-9_])*`

There are currently no restrictions on label values.

### PR DESCRIPTION
**Pull request by brian-brazil**
Document who's responsible for checking produced metrics are valid.

Closes #28 
@juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: in principle, but the build is failing with OOM. @brian-brazil @beorn7 Is lack of memory for Java client library tests a known issue?

**Comment by brian-brazil** [comment]
This happens a fair bit of the time on the pushgateway test. All tests are passing on my laptop.

**Comment by checketts** [comment]
This fix doesn't catch hyphens in the metric name.

`Gauge.build().name("a-b").labelNames("__name__").help("h").create();`

**Comment by brian-brazil** [comment]
Are you sure your're using a recent enough version of the code?

**Comment by checketts** [comment]
Sorry for leaving that off. I'm using version `0.0.19`

**Comment by checketts** [comment]
Oh my code snippet was misleading. My actual code (in an exporter) is doing:

`return new MetricFamilySamples(cleanName, Type.GAUGE, help, samples);`

So it is bypassing the check. Sorry for the noise.

**Comment by brian-brazil** [comment]
Custom collectors don't have sanity checks, it's up to you to ensure they're sane.

**Pull request merged**
