### PR TITLE
Add dokumentation on how to use `MetricServlet` with Google Guice DI.

### PR DESCRIPTION
**Pull request by goettl79**
Adds documentation on how to use the prom java client in an Google Guice Dependency Injection Environment.

### CODE REVIEW

**Comment by brian-brazil** [comment]
There's many many frameworks out there that each have their own way of dealing with a standard Servlet. I think it's best to presume that a user knows how this would work in their favourite framework, so there's no need to clutter the docs with multiple fragments of solutions.

If you want to share this information, I'd suggest a blog post or similar that can go into more depth than reference documentation like this.

**Comment by goettl79** [comment]
Hi Brian,

Understood. Just thought it might help.

Probably something that you could think about is to annotate the
MetricsServlet with the jsr-330 annotation "Singleton". This would make
integration simpler with guice and spring an might be reasonable too.

Regards, Georg


Brian Brazil <notifications@github.com> schrieb am Sa., 29. Apr. 2017,
16:22:

**Comment by brian-brazil** [comment]
The MetricsServlet is not a singleton, you can have as many of them as you like (though usually only one).

**Comment by checketts** [comment]
Another quick way to share your info would be to post a question on StackOverflow that you answer yourself.

**Pull request closed without merging**
