### PR TITLE
Update Gauge.java

### PR DESCRIPTION
**Pull request by jchprj**
Comment is Wrong

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?

**Comment by jchprj** [comment]
> Can you add the DCO?

OK, I'm learning the DCO.

**Comment by brian-brazil** [comment]
git commit --amend -s

**Comment by jchprj** [comment]
> git commit --amend -s

It's done. Thank you!

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
