### PR TITLE
Update StandardExports.java helper string for consistency

### PR DESCRIPTION
**Pull request by kevinyien**
updated client_java to match client_golang

https://github.com/prometheus/client_golang/issues/171

### CODE REVIEW

**Comment by brian-brazil** [comment]
There's more than that one that needs updating.

**Comment by kevinyien** [comment]
@brian-brazil apologies for missing that and making you double-back. Should be all set now.

**Comment by brian-brazil** [comment]
The memory and fds are also inconsistent.

**Comment by kevinyien** [comment]
@brian-brazil  finally got them all...

**Comment by brian-brazil** [comment]
Could you squash your commits please?

**Comment by kevinyien** [comment]
please ignore - will squash commits

**Comment by kevinyien** [comment]
@brian-brazil squashed

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
