### PR TITLE
#222

### PR DESCRIPTION
**Pull request by fedotxxl**
fixes https://github.com/prometheus/client_java/issues/222 (checked manually)

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is one place of several where this code is called, are all the others correct?

**Comment by fedotxxl** [comment]
how can I check it?

**Comment by brian-brazil** [comment]
Look at everywhere TextFormat.write004 is called.

**Comment by fedotxxl** [comment]
I didn't find any other place to fix

**Comment by brian-brazil** [comment]
Even https://github.com/prometheus/client_java/blob/master/simpleclient_servlet/src/main/java/io/prometheus/client/exporter/MetricsServlet.java#L40 ?

It seems odd to me that this would only be broken in one place.

**Comment by fedotxxl** [comment]
Sorry, I can't help here - I'm not a project maintainer. I can help to fix a problem after it will be reproduced. So I can try to check something. Please tell me what should be checked and I'll try to check it manually

**Comment by brian-brazil** [comment]
If you pass that flag and bring up a simple servlet to serve metrics, does it reproduce the problem you say?

**Comment by pjfanning** [comment]
http://docs.oracle.com/javaee/6/api/javax/servlet/ServletResponse.html#setCharacterEncoding(java.lang.String) seems to indicate that MetricsServlet should be ok- since the Prometheus content type has charset=utf-8.

**Comment by pjfanning** [comment]
@fedotxxl you might be able to workaround the issues by setting `-Dfile.encoding=utf-8` in your batch script (that runs the java command).

**Comment by fedotxxl** [comment]
@pjfanning yep, already fixed this way

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
