### PR TITLE
Adding TraceSampling to Examplar Sampler

### PR DESCRIPTION
**Pull request by fscellos**
This PR answer to Issue #765 (finally short so i do it shortly too)
@fstab

### CODE REVIEW

**Comment by fscellos** [comment]
Hello @fstab. Have you any comments ?

**Review by fstab — CHANGES_REQUESTED** [review]
Thanks a lot for the PR and sorry for the delay with the review.

It's looking great, I added a few minor comments, but apart from that it's good.

**Comment by fscellos** [comment]
Thank you for your feedback. I'll do it in one week or two.

**Comment by fscellos** [comment]
Hello @fstab.
I have taken into account your suggestions. I let you check.

**Comment by fscellos** [comment]
Hello @fstab .Any news ? Does modification ok for you ?

**Comment by fstab** [comment]
Thanks a lot, and sorry for the delay.

**Pull request merged**
