### PR TITLE
added /prometheus as a Spring Boot Endpoint

### PR DESCRIPTION
**Pull request by eliezio**
fixed doc issues

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

**Comment by fiunchinho** [comment]
When will this released? Thanks!

**Comment by brian-brazil** [comment]
Next week sometime is the plan.

**Comment by fiunchinho** [comment]
I was trying to test it locally just copy and pasting the files from this pull request, but I can't get it to work properly. After adding the `@EnablePrometheusEndpoint()` annotation to my Application, I can visit the `/prometheus` endpoint but with empty result.
The `/metrics` endpoint is returning the usual response.

prometheus

Do I need to do anything else?

**Comment by eliezio** [comment]
The metrics you are seeing through the /metrics endpoint are those that were auto-configured by Spring Boot.
To see these metrics also through /prometheus endpoint, you need to instantiate a SpringBootMetricsCollector bean as stated on its documentation (see https://prometheus.io/client_java/io/prometheus/client/spring/boot/SpringBootMetricsCollector.html).
Maybe there should be a second annotation (i.e.: @ExportPublicMetricsToPrometheus) to simplify this task.

**Comment by fiunchinho** [comment]
You are right. It works now, thank you very much

**Pull request merged**
