### PR TITLE
Support direct access to com.sun.management.OperatingSystemMXBean

### PR DESCRIPTION
**Pull request by PaulSandoz**
Obtaining the counter metric process_cpu_seconds_total fails on Java 9 because the setAccessible call throws an Exception.  This is because the reflective method is obtained from the concrete implementing class rather than the interface. In Java 9 classes may be encapsulated within a module and not exported and therefore not accessible.

We can check that the OS bean is an instance of com.sun.management.OperatingSystemMXBean (as is already done for com.sun.management.UnixOperatingSystemMXBean, the latter inherits from the former).

For interface com.ibm.lang.management.OperatingSystemMXBean we still need to perform reflective access but we should operate on the method whose declaring class is that interface to ensure access (note i have not tested this since i don't have a distribution of the IBM JDK).

### CODE REVIEW

**Comment by brian-brazil** [comment]
This looks okay to me in principle.

@davidkarlsen Can you confirm this still works on IBM Java?

**Comment by davidkarlsen** [comment]
A bit disconnected from the grid until the weekend - if it compiles with an IBM JDK 7/8 (or whatever lower-boundary for JDK version) it should be ok - but I suspect the class might not be present on an IBM JDK.

**Comment by alin-amana** [comment]
OK, tested against both JREs and the Simpleclient/Simpleclient Hotspot tests passed.

FYI, on Java 9 I got some different test failures deep in Spring code:
$ JAVA_HOME=~/Work/jre/jre-9 ./mvnw test
...
Running io.prometheus.client.spring.web.MethodTimerTest
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.277 sec <<< FAILURE! - in io.prometheus.client.spring.web.MethodTimerTest
testOverloadedMethodName(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.186 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.getProxy(MethodTimerTest.java:48)
	at io.prometheus.client.spring.web.MethodTimerTest.testOverloadedMethodName(MethodTimerTest.java:191)

testThrowWorks(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.getProxy(MethodTimerTest.java:48)
	at io.prometheus.client.spring.web.MethodTimerTest.testThrowWorks(MethodTimerTest.java:121)

testSecondMethod(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.getProxy(MethodTimerTest.java:48)
	at io.prometheus.client.spring.web.MethodTimerTest.testSecondMethod(MethodTimerTest.java:151)

timeMethod(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.timeMethod(MethodTimerTest.java:36)

testValueParam(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.getProxy(MethodTimerTest.java:48)
	at io.prometheus.client.spring.web.MethodTimerTest.testValueParam(MethodTimerTest.java:55)

testHelpParam(io.prometheus.client.spring.web.MethodTimerTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut timeable
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190)
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169)
	at org.springframework.aop.support.ComposablePointcut.<init>(ComposablePointcut.java:66)
	at org.springframework.aop.support.Pointcuts.union(Pointcuts.java:52)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:92)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:209)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:136)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAdvisorsFromAspectInstanceFactory(AspectJProxyFactory.java:121)
	at org.springframework.aop.aspectj.annotation.AspectJProxyFactory.addAspect(AspectJProxyFactory.java:111)
	at io.prometheus.client.spring.web.MethodTimerTest.getProxy(MethodTimerTest.java:48)
	at io.prometheus.client.spring.web.MethodTimerTest.testHelpParam(MethodTimerTest.java:85)


Results :

Tests in error: 
  MethodTimerTest.testOverloadedMethodName:191->getProxy:48 » IllegalArgument er...
  MethodTimerTest.testThrowWorks:121->getProxy:48 » IllegalArgument error at ::0...
  MethodTimerTest.testSecondMethod:151->getProxy:48 » IllegalArgument error at :...
  MethodTimerTest.timeMethod:36 » IllegalArgument error at ::0 can't find refere...
  MethodTimerTest.testValueParam:55->getProxy:48 » IllegalArgument error at ::0 ...
  MethodTimerTest.testHelpParam:85->getProxy:48 » IllegalArgument error at ::0 c...

Tests run: 6, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Prometheus Java Suite .............................. SUCCESS [  0.181 s]
[INFO] Prometheus Java Simpleclient ....................... SUCCESS [  4.100 s]
[INFO] Prometheus Java Simpleclient Common ................ SUCCESS [  0.377 s]
[INFO] Prometheus Java Simpleclient Caffeine .............. SUCCESS [  0.652 s]
[INFO] Prometheus Java Simpleclient Dropwizard ............ SUCCESS [  0.356 s]
[INFO] Prometheus Java Simpleclient Graphite Bridge ....... SUCCESS [  0.333 s]
[INFO] Prometheus Java Simpleclient Hibernate ............. SUCCESS [  0.985 s]
[INFO] Prometheus Java Simpleclient guava ................. SUCCESS [  0.499 s]
[INFO] Prometheus Java Simpleclient Servlet ............... SUCCESS [  0.901 s]
[INFO] Prometheus Java Simpleclient Hotspot ............... SUCCESS [  0.601 s]
[INFO] Prometheus Java Simpleclient Httpserver ............ SUCCESS [  0.437 s]
[INFO] Prometheus Java Simpleclient log4j ................. SUCCESS [  0.358 s]
[INFO] Prometheus Java Simpleclient log4j2 ................ SUCCESS [  0.453 s]
[INFO] Prometheus Java Simpleclient logback ............... SUCCESS [  0.386 s]
[INFO] Prometheus Java Simpleclient Pushgateway ........... SUCCESS [ 14.909 s]
[INFO] Prometheus Java Simpleclient Spring Metrics ........ FAILURE [  0.630 s]
[INFO] Prometheus Java Simpleclient Spring Boot Metric .... SKIPPED
[INFO] Prometheus Java Simpleclient Jetty ................. SKIPPED
[INFO] Prometheus Java Simpleclient Jetty JDK 8 ........... SKIPPED
[INFO] Prometheus Java Simpleclient Vert.x ................ SKIPPED
[INFO] Prometheus Java Client Benchmarks .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.729 s
[INFO] Finished at: 2017-07-27T17:42:49+02:00
[INFO] Final Memory: 18M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project simpleclient_spring_web: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/alin/Work/prometheus_client_java/simpleclient_spring_web/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :simpleclient_spring_web

**Comment by brian-brazil** [comment]
Superseded by #281

**Pull request closed without merging**
