### PR TITLE
instrumentation-dw5: Fix metric name issue with CustomLabelMapper

### LINKED ISSUE #947: dropwizard5 MapperConfig doesn't rename the metric?
I'm not a java dev so bear with me.. but I think there's an issue with the dropwizard5 MapperConfig use:

https://github.com/prometheus/client_java/blob/main/prometheus-metrics-instrumentation-dropwizard5/src/main/java/io/prometheus/metrics/instrumentation/dropwizard5/labels/MapperConfig.java#L44

This says that you can specify a name to rename the resulting metric (e.g. after matching with wildcards like in the example) - but this doesn't seem to actually do anything?

You can see this in the tests too, e.g.:

https://github.com/prometheus/client_java/blob/main/prometheus-metrics-instrumentation-dropwizard5/src/test/java/io/prometheus/metrics/instrumentation/dropwizard5/labels/CustomLabelMapperTest.java#L107

```
        final MapperConfig mapperConfig = new MapperConfig(
                "app.okhttpclient.client.HttpClient.*.*",
                "app.okhttpclient.client.HttpClient",
                labels
        );
```
This should name the metric `app.okhttpclient.client.HttpClient` according to the code comments, but in the tests you can see it tests that it's equal to its original name and not the set name:
```
        String expected = "# TYPE app_okhttpclient_client_HttpClient_greatService_400 counter\n" +

                                                                     ^^^^^^^^^^^^^^^^  this wouldn't be here if it was renamed
```

I also see this in practice when writing my own code too - just the test makes it easy to verify.   The labels work, just the name doesn't seem to ever get referenced and actually used as a rename.

Is this a known issue or limitation?

Thanks!

### PR DESCRIPTION
**Pull request by kingster**
Fixes #947

### CODE REVIEW

**Comment by andycoates** [comment]
Hey @kingster - let me know if I've interpreted these issues correctly (not a java dev so hard follow in some cases):

1) One thing that I noticed which was making this harder to compare is that the `HELP` and `TYPE` lines don't match the metric name in basic type cases - is this just something odd with the test helpers?  Or the broader prometheus exposition format conversion? (e.g. histogram has `_bucket` `_sum` and `_count`, while summary just uses `_sum` and `_count` - so I'd expect the `HELP` and `TYPE` names to be the base metric name in those types - but not the others).

As an example to demonstrate, from the 2nd test `test_WHEN_NoMatches_THEN_ShouldReturnDefaultSample`:
```
        String expected = "# TYPE app_okhttpclient_client_HttpClient_service counter\n" +
                "# HELP app_okhttpclient_client_HttpClient_service Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.service.total, type=io.dropwizard.metrics5.Counter)\n" +
                "app_okhttpclient_client_HttpClient_service_total 1.0\n" +
                "# EOF\n";
```
In that test case the name isn't specified so would be based on underlying metric name:
```
metricRegistry.counter("app.okhttpclient.client.HttpClient.service.total").inc(1);
```
so the metric name came out correct, but its like it stripped `_total` off in the `HELP` and `TYPE`.  That `_total` comes up later in other test issues - so maybe related.

2) `test_WHEN_MoreMatchesReverseOrder_THEN_ShouldReturnFirstOne` - this one makes my eyes go crossed lol.. I'm not sure what the intent is as the `labelMapperList` list looks the same ordering as the test before it, but:
```
                new MapperConfig("app.okhttpclient.client.HttpClient.*.total") // this matches as well
```
it wouldn't actually match, the metric used is:
```
        metricRegistry.counter("app.okhttpclient.client.HttpClient.greatService.400").inc(1);
```
That aside, the `MetricConfig` it does match sets the name to `app.okhttpclient.client.HttpClient`:
```
        final MapperConfig mapperConfig = new MapperConfig(
                "app.okhttpclient.client.HttpClient.*.*",
                "app.okhttpclient.client.HttpClient",
                labels
        );
```
but the output comparison has a `_total` in the metric name????  I'm confused where that even comes from:
```
        String expected = "# TYPE app_okhttpclient_client_HttpClient counter\n" +
                "# HELP app_okhttpclient_client_HttpClient Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.greatService.400, type=io.dropwizard.metrics5.Counter)\n" +
                "app_okhttpclient_client_HttpClient_total{service=\"greatService\",status=\"400\"} 1.0\n" +
                "# EOF\n";
```
3. Likewise in `test_WHEN_MoreToFormatInLabelsAndName_THEN_ShouldReturnCorrectSample` the "this matches as well" wouldn't match.  In the output there's the weird `_total` suffix again (but otherwise the metric would have been renamed properly to include the match in the name).

4. Again `test_WHEN_AdditionalLabels_THEN_ShouldReturnCorrectSample` the "this matches as well" wouldn't, but also the metric name comes out wrong - it shouldn't have the `_400` as the name is set to just use `${0}` which is `greatService`.  


I think that covers all I can see at first pass - thanks for helping with this!

**Comment by andycoates** [comment]
> Yes, this is the behavior that comes from how the TYPE line is created. This comes from `sanitizeMetricName` which strips those to make it a valid prometheus type name.

Not related to this specific fix then, but I believe what it's doing is wrong?
https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information - says it should be the metric name after `HELP` and `TYPE`, not a sanitized one that may make it different than the actual metric name?

If you look at JMX instrumentation from this library it keeps them the same - e.g.
```
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 7045.0
```


> `app.okhttpclient.client.HttpClient.greatService.400` gets converted to `app_okhttpclient_client_HttpClient_total{service=\"greatService\",status=\"400\"}` where both status and service are labels.

but...
```
                new MapperConfig("app.okhttpclient.client.HttpClient.*.total") // this matches as well
```
doesn't match (which is the point of the tests for multiple matches) - you can verify by just taking out the properly constructed MapperConfig and leaving the above, it shows:
```
test_WHEN_MoreMatchesReverseOrder_THEN_ShouldReturnFirstOne(io.prometheus.metrics.instrumentation.dropwizard5.labels.CustomLabelMapperTest)  Time elapsed: 0.054 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...nt_client_HttpClient[ counter
# HELP app_okhttpclient_client_HttpClient Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.greatService.400, type=io.dropwizard.metrics5.Counter)
app_okhttpclient_client_HttpClient_total{service="greatService",status="400"}] 1.0
# EOF
> but was:<...nt_client_HttpClient[_greatService_400 counter
# HELP app_okhttpclient_client_HttpClient_greatService_400 Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.greatService.400, type=io.dropwizard.metrics5.Counter)
app_okhttpclient_client_HttpClient_greatService_400_total] 1.0
# EOF
>
```
You can see above it didn't match because the metric name remained as the converted prometheus version (underscore etc) `app.okhttpclient.client.HttpClient.greatService.400` => `app_okhttpclient_client_HttpClient_greatService_400_total`

The "this matches as well" isn't matching for the purpose of adding extra match cases in those test cases.  I think you changed the metric name for the test but left that in?

**Comment by kingster** [comment]
> Not related to this specific fix then, but I believe what it's doing is wrong? https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information - says it should be the metric name after `HELP` and `TYPE`, not a sanitized one that may make it different than the actual metric name?
> 
> If you look at JMX instrumentation from this library it keeps them the same - e.g.
> 
> ```
> # HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
> # TYPE jvm_classes_loaded_total counter
> jvm_classes_loaded_total 7045.0
> ```
> 

However, that is not what the client_java library does, here is an example using the native models

```java
 Counter requestCount = Counter.builder()
                .name("requests_total")
                .help("Total number of requests")
                .labelNames("path", "status")
                .register();
        requestCount.labelValues("/hello-world", "200").inc();
        System.out.println(convertToOpenMetricsFormat(PrometheusRegistry.defaultRegistry.scrape()));
```

Gives output

```
# TYPE requests counter
# HELP requests Total number of requests
requests_total{path="/hello-world",status="200"} 1.0
requests_created{path="/hello-world",status="200"} 1712646477.091
requests_total{path="/hello-world",status="500"} 1.0
requests_created{path="/hello-world",status="500"} 1712646477.097
# EOF
```

So I would let @fstab  respond here, but IMO this is how the java client is designed to behave.


> ```
> test_WHEN_MoreMatchesReverseOrder_THEN_ShouldReturnFirstOne(io.prometheus.metrics.instrumentation.dropwizard5.labels.CustomLabelMapperTest)  Time elapsed: 0.054 sec  <<< FAILURE!
> org.junit.ComparisonFailure: expected:<...nt_client_HttpClient[ counter
> # HELP app_okhttpclient_client_HttpClient Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.greatService.400, type=io.dropwizard.metrics5.Counter)
> app_okhttpclient_client_HttpClient_total{service="greatService",status="400"}] 1.0
> # EOF
> > but was:<...nt_client_HttpClient[_greatService_400 counter
> # HELP app_okhttpclient_client_HttpClient_greatService_400 Generated from Dropwizard metric import (metric=app.okhttpclient.client.HttpClient.greatService.400, type=io.dropwizard.metrics5.Counter)
> app_okhttpclient_client_HttpClient_greatService_400_total] 1.0
> # EOF
> >
> ```
> 
> You can see above it didn't match because the metric name remained as the converted prometheus version (underscore etc) `app.okhttpclient.client.HttpClient.greatService.400` => `app_okhttpclient_client_HttpClient_greatService_400_total`
> 
> The "this matches as well" isn't matching for the purpose of adding extra match cases in those test cases. I think you changed the metric name for the test but left that in?

I don't get this error, and this is not reported in the CI either. Can you try again maybe?

**Comment by andycoates** [comment]
> However, that is not what the client_java library does

It does though? those metrics were from `prometheus-metrics-instrumentation-jvm`, unless it does something different... i.e. if I:
```
import io.prometheus.metrics.instrumentation.jvm.JvmMetrics;

[...]

        JvmMetrics.builder().register(registry);
        DropwizardExports.builder()
            .dropwizardRegistry(metricsRegistry)
            .customLabelMapper(labelMapper)
            .register(registry);
```
then it produces hundreds of JVM metrics along with my dropwizard metrics, and all the JVM ones have the metric name the same in `HELP` and `TYPE` and the actual output.

A small selection from `JvmMetrics`:
```
# HELP jvm_buffer_pool_capacity_bytes Bytes capacity of a given JVM buffer pool.
# TYPE jvm_buffer_pool_capacity_bytes gauge
jvm_buffer_pool_capacity_bytes{pool="direct"} 109616.0
jvm_buffer_pool_capacity_bytes{pool="mapped"} 0.0
# HELP jvm_buffer_pool_used_buffers Used buffers of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_buffers gauge
jvm_buffer_pool_used_buffers{pool="direct"} 2.0
jvm_buffer_pool_used_buffers{pool="mapped"} 0.0
# HELP jvm_buffer_pool_used_bytes Used bytes of a given JVM buffer pool.
# TYPE jvm_buffer_pool_used_bytes gauge
jvm_buffer_pool_used_bytes{pool="direct"} 109616.0
jvm_buffer_pool_used_bytes{pool="mapped"} 0.0
# HELP jvm_classes_currently_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_currently_loaded gauge
jvm_classes_currently_loaded 7045.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 7045.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
```


> I don't get this error, and this is not reported in the CI either. Can you try again maybe?

Sorry maybe I'm confusing things - I was just using that test as an example to show that:
```
                new MapperConfig("app.okhttpclient.client.HttpClient.*.total"), // this matches as well
```
doesn't actually match the metric you used:
```
        metricRegistry.counter("app.okhttpclient.client.HttpClient.greatService.400").inc(1);
```
It doesn't affect the test case because it never gets to that MapperConfig "this matches as well" - all I'm saying is that wouldn't actually match anyway, and is used in a few other tests.

**Comment by kingster** [comment]
> Sorry maybe I'm confusing things - I was just using that test as an example to show that:
> 
> ```
>                 new MapperConfig("app.okhttpclient.client.HttpClient.*.total"), // this matches as well
> ```
> 
> doesn't actually match the metric you used:
> 
> ```
>         metricRegistry.counter("app.okhttpclient.client.HttpClient.greatService.400").inc(1);
> ```
> 
> It doesn't affect the test case because it never gets to that MapperConfig "this matches as well" - all I'm saying is that wouldn't actually match anyway, and is used in a few other tests.

Thanks for pointing, this updated the matcher, it should correctly match now. The test's should be comprehensive now.


> It does though? those metrics were from `prometheus-metrics-instrumentation-jvm`, unless it does something different... i.e. if I:
> 
> ```
> import io.prometheus.metrics.instrumentation.jvm.JvmMetrics;
> 
> [...]
> 
>         JvmMetrics.builder().register(registry);
>         DropwizardExports.builder()
>             .dropwizardRegistry(metricsRegistry)
>             .customLabelMapper(labelMapper)
>             .register(registry);
> ```
> 
> then it produces hundreds of JVM metrics along with my dropwizard metrics, and all the JVM ones have the metric name the same in `HELP` and `TYPE` and the actual output.
> 
> A small selection from `JvmMetrics`:
> 
> ```
> # HELP jvm_buffer_pool_capacity_bytes Bytes capacity of a given JVM buffer pool.
> # TYPE jvm_buffer_pool_capacity_bytes gauge
> jvm_buffer_pool_capacity_bytes{pool="direct"} 109616.0
> jvm_buffer_pool_capacity_bytes{pool="mapped"} 0.0
> # HELP jvm_buffer_pool_used_buffers Used buffers of a given JVM buffer pool.
> # TYPE jvm_buffer_pool_used_buffers gauge
> jvm_buffer_pool_used_buffers{pool="direct"} 2.0
> jvm_buffer_pool_used_buffers{pool="mapped"} 0.0
> # HELP jvm_buffer_pool_used_bytes Used bytes of a given JVM buffer pool.
> # TYPE jvm_buffer_pool_used_bytes gauge
> jvm_buffer_pool_used_bytes{pool="direct"} 109616.0
> jvm_buffer_pool_used_bytes{pool="mapped"} 0.0
> # HELP jvm_classes_currently_loaded The number of classes that are currently loaded in the JVM
> # TYPE jvm_classes_currently_loaded gauge
> jvm_classes_currently_loaded 7045.0
> # HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
> # TYPE jvm_classes_loaded_total counter
> jvm_classes_loaded_total 7045.0
> # HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
> # TYPE jvm_classes_unloaded_total counter
> jvm_classes_unloaded_total 0.0
> ```

These are mostly gauge's where the metric name are predefined and matches.  However for metrics which are defined by code, for those the behavior is different as I explained earlier. Probably @fstab can share some insights why there is this difference.

**Comment by fstab** [comment]
Not a Dropwizard expert, but here's some context on the `_total` suffix for counters: This is defined in the [OpenMetrics standard](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#counter-1):

> The MetricPoint's Total Value Sample MetricName MUST have the suffix "_total". If present the MetricPoint's Created Value Sample MetricName MUST have the suffix "_created".

The `HELP` and `TYPE` do not have the suffix, this is also defined in OpenMetrics.

The Prometheus server scrapes metrics in OpenMetrics format, i.e. the scrape request has an `Accept: application/openmetrics-text` header.

**Comment by andycoates** [comment]
> IMHO we should merge if the bug is fixed here. The `HELP` & `TYPE` are just metadata which can be raised as separate issue and solve it across all instrumentation implementations if required.

Agreed - thanks for the fixes, and those test cases are easier to read now 👍

**Review by fstab — APPROVED** [review]
Thanks a lot for the fix and for the discussion! Highly appreciated.

**Pull request merged**
