### PR TITLE
Add Gradle assets to README

### PR DESCRIPTION
**Pull request by amdelamar**
@beorn7 - Just adding to the README. :)

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. The existing examples has to be updated by hand on every release, and I'd prefer not to have additional updates to do.

**Comment by amdelamar** [comment]
Ok let's improve it then.

We can substitute variables for the version numbers. Like so:

```gradle
dependencies {
    compile 'io.prometheus:simpleclient:' + prometheusVersion
}
```

We can do the same for Maven:

```xml
<dependencies>
  ...
  <dependency>
    <groupId>io.prometheus</groupId>
    <artifactId>simpleclient</artifactId>
    <version>${prometheus.version}</version>
  </dependency>
  ...
</dependencies>
```

**Comment by brian-brazil** [comment]
That would stop the current list being copy&pasteable.

**Comment by amdelamar** [comment]
True. But its a common way of listing assets.

Example: [fluent/fluent-logger-java](https://github.com/fluent/fluent-logger-java)

**Comment by brian-brazil** [comment]
That's not what I'm aiming for here, I like things to be as copy&pastable as possible to reduce friction.

**Comment by amdelamar** [comment]
Ok. No problem. We'll close it then for now

**Pull request closed without merging**
