### PR TITLE
#887 otlp exporter exemplars

### PR DESCRIPTION
**Pull request by 0x006EA1E5**
@fstab 
This PR adds support for exemplars in the OTLP Exporter
Addressed https://github.com/prometheus/client_java/issues/877

The change seems fairly trivial, but I wonder if we need more test coverage?

### CODE REVIEW

**Comment by 0x006EA1E5** [comment]
Is there a reason why we are using JUnit 4, not 5?

**Review by fstab — CHANGES_REQUESTED** [review]
Thanks a lot, it's looking great.

One tiny thing: There's an empty file `trace.proto` which I think is not needed.

Regarding tests: I like your test, it's a good way to test this. I know that test coverage of the OTel exporter is currently not great. For the Prometheus formats the `ExpositionFormatsTest` is much more complete, but it was also a lot of work :).

> Is there a reason why we are using JUnit 4, not 5?

No, it's just that nobody updated it. If you like to create a PR: I'd appreciate an update to JUnit 5 :)

**Comment by 0x006EA1E5** [comment]
> One tiny thing: There's an empty file trace.proto which I think is not needed.

Removed, sorry about that

**Comment by 0x006EA1E5** [comment]
@fstab Are there any more actions you need me to do here? Is it suitable to me merged as is?

**Review by fstab — APPROVED** [review]
Looks great, thanks a lot!

**Pull request merged**
