### PR TITLE
Fix NullPointerException

### PR DESCRIPTION
**Pull request by JWThewes**
Fix NPE when invoking MVCEndpoint without a name parameter

### CODE REVIEW

**Comment by brian-brazil** [comment]
Did #256 not fix this?

**Comment by brian-brazil** [comment]
I'm presuming this was already fixed.

**Comment by JWThewes** [comment]
@brian-brazil Oh I'm totally sorry. Forgot to add a note...
Of course #256 fixed it. Just another solution of fixing it but it works.
Sorry :(

**Comment by brian-brazil** [comment]
No problem at all, PRs fixing things are always welcome.

**Pull request closed without merging**
