### PR TITLE
allowing to keep invalid counter names (with no _total suffix)

### PR DESCRIPTION
**Pull request by ndimitry**
In some cases keeping broken counter names (with no _total suffix) will be really helpful. For example when old names are documented and are in use with a lot of dashboards being precreated for them. Or in case it is sugnificant not to loose connection to old data when counters are renamed.

Possibly this might be a grace option allowing some grace period (for a year or two) for the teams to move to the new names. For us this is quite an effort shared between several development teams. And we are afraid that OpenMetrics format might change too because it is still an RFC draft. When OpenMetrics are becoming an RFC this will be steady argument for us to move to this format.

Links to the discussions https://github.com/prometheus/client_java/issues/640, https://github.com/prometheus/client_java/issues/649

### CODE REVIEW

**Comment by ndimitry** [comment]
@fstab please, review

**Comment by fstab** [comment]
Hi, I finally got back to this, and I have a few points:

* The property only affects the text format 004, not the OpenMetrics format. This is good, because in OpenMetrics a counter without the `_total` prefix would be invalid. However, as far as I know there is no way to make a new Prometheus server release use the old format, as the `Accept` header is hard-coded here https://github.com/prometheus/prometheus/blob/03b354d4d9386e4b3bfbcd45da4bb58b182051a5/scrape/scrape.go#L686-L686. As soon as you switch to a new version of Prometheus you will have the `_total` suffix again.
* The change removes `_total` from all counters, even if there is a counter explicitly named `_total`.

Instead of starting the monitored application with `-Dio.prometheus.allowInvalidCounterNames=true` you could achieve the same effect by adding the following to your Prometheus scrape config:

```yaml
   metric_relabel_configs:
    - source_labels: [__name__]
      regex:  '(.*)_total'
      target_label: __name__
      replacement: '${1}'
```

Given the new issues this PR would introduce (result depends on the Prometheus version, and it is no longer possible to name a counter `..._total` I think it might be better to use a relabel config as a temporary fix until dashboards are adapted.

**Comment by ndimitry** [comment]
@fstab thank you for the possible workaround description!

I guess, let's have this pull request closed then...

**Comment by travisspencer** [comment]
I agree with @franck102. This should be reopened. Upgrading to 0.12 was required to get Jakarta servlet support (cf. #647), but this breaking change came in at the same time. Now, we're blocked -- we can't upgrade Jetty to v. 11 because that requires Jakarta not javax servlets, but upgrading this lib to work with the new Jetty version brings in this breaking change.

What I don't understand is how the resource representation changes if the client keeps asking for `text/plain; version=0.0.4`. If my client keeps negotiating that format, why does it get anything different? Seems it's not really `0.0.4` format any more (or the version is unstable).

Help in resolving this conundrum is much appreciated.

**Comment by travisspencer** [comment]
@fstab , can you or one of the other maintainers of this project comment on my previous input? WDYT?

**Comment by fstab** [comment]
Setting `io.prometheus.allowInvalidCounterNames=true` will remove the `_total` suffix from all counters, even if there is a counter explicitly named `_total`. So if you now have an issue with `_total` suffixes being added to all counters, with this PR you might run into an issue because `_total` suffixes are removed from all counters.

**Comment by travisspencer** [comment]
That sounds like it could still produce a breaking change, @fstab , if I have counters named `..._total` already. I will check this, but would like to know which property I need to set or how I can use this library to make it work as it did in the previous version. If that's not doable, can the Jakarta support be back-ported?

**Comment by fstab** [comment]
No, I am talking about this PR here: If we merge this PR, then we'll get a property `io.prometheus.allowInvalidCounterNames` that would remove all `_total` suffixes from counters. That's why I don't want to re-open this.

**Comment by travisspencer** [comment]
Ah, I see your point, @fstab. I think then what should be reopened is #640. (I should have made my comment there and not on this PR, it seems.) Would you agree with reopening that issue?

**Comment by JnRouvignac** [comment]
I agree that this PR may not be the right way to restore the old behaviour with respect to counter metric names.

I could start working on a new PR that adds a `io.prometheus.allowInvalidCounterNames` system property to restore the older behaviour.
Would you agree with merging such a PR @fstab if it satisfied you?

**Comment by JnRouvignac** [comment]
I have noticed #791 which adds `PROMETHEUS_DISABLE_CREATED_SERIES`, so I think the answer is yes.
I'll look into doing a PR to allow smoother migration.
Thanks.

**Pull request closed without merging**
