### PR TITLE
#529: Expose HTTPMetricHandler

### PR DESCRIPTION
**Pull request by janssk1**

### CODE REVIEW

**Comment by brian-brazil** [comment]
This change is bigger than it needs to be, you only needed to change the visibility.

**Comment by janssk1** [comment]
Created it as a toplevel class. That makes it clear that the handler is a standalone class. Instantiating HttpServer.HTTPMetricHandler might indicate that a server is still involved. 
Given that there are good tests, moving a class should not be problem.

**Comment by brian-brazil** [comment]
I'm not sure how good our tests are here, and I'd don't like splitting logic like this across files too much.

**Comment by brian-brazil** [comment]
Given that my comments remain unaddressed I'm going to close this off. If you're still interesting in a change that only makes this public, let me know.

**Pull request closed without merging**
