### PR TITLE
Remove trailing comma from label values

### PR DESCRIPTION
**Pull request by marcust**
Looks untidy. I was just wondering if I broke something because of that, so I decided to fix that

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is permitted by the spec.

**Comment by checketts** [comment]
@marcust See #210  #351 #321 #262

**Comment by marcust** [comment]
Well if it is permitted is not the point, no? The point is that I apparently was the fifth person that got confused by that at looked for a bug that wasn't there. Kudos to Prometheus to accepting that as input, but why would you write something that looks odd, even if it is permitted by the spec?

**Comment by himanshub16** [comment]
I get that trailing comma in last label is not an error, and is permitted by spec.
However, I have tested `python`, and `golang` clients, and they don't have such behaviour.
Also, it looks weird to have something of a JSON-like structure and have a trailing comma to the last item.

Thoughts?

**Comment by adigupta13** [comment]
Completely agree with @marcust . The fact that everyone is confused with this behaviour and is not consistent with other platform clients like python and golang should be enough reason to fix it even if it is supported in the spec. And no acknowledgment by @brian-brazil since 3 years doesn't look good.

**Pull request closed without merging**
